server:
  port: 9001
spring:
  application:
    name: dym-sellergoods
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.206.110:33306/dongyimaidb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.206.110
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
          strategy: SEMAPHORE    #使用Seamphore，你创建了多少线程，实际就会有多少线程进行执行，只是可同时执行的线程数量会受到限制
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰式编写规范
  type-aliases-package: com.offcn.sellergoods.pojo
# 配置sql打印日志
logging:
  level:
    com.offcn: debug