server:
  port: 9005
spring:
  application:
    name: dym-search
  elasticsearch:
    rest:
      uris: 192.168.206.110:9200  #此处配置elasticsearch的访问地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
#超时配置
ribbon:
  ReadTimeout: 300000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
logging:
  level:
    com.offcn: debug
