server:
  port: 9003
spring:
  application:
    name: dym-canal
  main:
    #允许多次注册feign
    allow-bean-definition-overriding: true
  redis:
    host: 192.168.206.110
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: true
        isolation:
          strategy: SEMAPHORE
#canal配置
canal:
  client:
    instances:
      example:
        host: 192.168.206.110
        port: 11111
logging:
  level:
   com.offcn: debug