spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  application:
    name: dym-file
server:
  port: 9002
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

FILE_SERVER_URL: http://192.168.206.110:8080/