server:
  port: 9102
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
#超时配置
ribbon:
  ReadTimeout: 300000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
spring:
  thymeleaf:
    cache: false
  application:
    name: dym-item-web
  main:
    allow-bean-definition-overriding: true

# 生成静态页的位置
pagepath: D:\\items